# This is a TOML document.

[machines]
    port = 22
    prefix = "fqdn.local"
    names = [
#    "1.1.1.1",
#   "machine-dev-001",
    "machine-dev-002",
    "machine-dev-003",
    "machine-dev-004",
    "machine-dev-005",
    "machine-dev-006",
#   "machine-dev-007",
    "machine-dev-008",
    "machine-dev-009",
    "machine-dev-010",
    "machine-dev-011",
    "machine-dev-012",
    "machine-dev-013",
    "machine-dev-014",
    "machine-dev-015",
#   "machine-dev-016",

]
